Upgrade to ap-light 0.6.0
This largely involved changing code to /opt/ap.

diff --git a/service/daas/bin/ldap-manage b/service/daas/bin/ldap-manage
--- a/service/daas/bin/ldap-manage
+++ b/service/daas/bin/ldap-manage
@@ -7,29 +7,19 @@ preStart() {
     exit 0
 }
 
-kdcHealth() {
-    _log "No kdc health method implemented"
+# Check if a member of a raft. If consul info returns an error we'll
+# pipefail and exit for a failed health check.
+# If we have no peers then try to join the raft via the CNS svc record.
+# Once a node is connected to at least one other peer it'll get the rest
+# of the raft via the Consul LAN gossip.
+# If we end up joining ourselves we just retry on the next health check
+# until we've got the whole cluster together.
+health() {
     exit 0
 }
-
-kdcMasterHealth() {
-    _log "No kdc-master health method implemented"
-    exit 0
-}
-
-kadminHealth() {
-    _log "No kadmin health method implemented"
-    exit 0
-}
-
-kpasswdHealth() {
-    _log "No kpasswd health method implemented"
-    exit 0
-}
-
 
 _log() {
-    echo "kerberos: $@"
+    echo "ldap: $@"
 }
 
 # ---------------------------------------------------
